estoque/estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index 

urlpatterns = [
    path('', index, name='index'),
    path('produto/',include('produto.urls',namespace='produto')),
    path('entrada/',include('entrada.urls',namespace='entrada')),
    path('saida/',include('saida.urls',namespace='saida')),
    path('admin/', admin.site.urls),
]

estoque/saida/urls.py
from django.urls import path
from .views import *


app_name ='saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida,name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida,name='delete_saida'),
]

estoque/saida/models.py
from django.db import models
from produto.models import Produtos
# Create your models here.
class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE,verbose_name='Produto')
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'saida'
        verbose_name_plural = 'saidas'
        ordering = ['-produto']

estoque/saida/forms.py
from django.forms import ModelForm
from .models import Saidas

class SaidasForm(ModelForm):
    class Meta:
        model = Saidas
        fields = ['produto', 'quantidade', 'preco']

estoque/saida/views.py
from django.shortcuts import render, redirect
from .models import Saidas
from .forms import SaidasForm
from django.http import HttpResponse
from django.urls import reverse
from django.contrib import messages
# Create your views here.
def list_saida(request):
    saidas = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
    'saidas': saidas,
    }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidasForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['produto'].quantidade < form.cleaned_data['quantidade']:
                messages.error(request,f'Por favor insira um valor até {form.cleaned_data["produto"].quantidade }')
                return redirect('saida:new_saida')
            form.save(commit=False)
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
        
            return redirect('saida:list_saida')
    else:
        template_name = 'new_saida.html'
        context = {
        'form': SaidasForm(),
        }
        return render(request, template_name, context)

def update_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    quantidade_anterior = saida.quantidade
    if request.method == 'POST':
        form = SaidasForm(request.POST, instance=saida)
        if form.is_valid():
            produto = form.cleaned_data['produto']
            quantidade_atual = form.cleaned_data['quantidade']
            diferenca = quantidade_atual - quantidade_anterior
            produto.quantidade -= diferenca
            produto.save()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'update_saida.html'
        context = {
            'form': SaidasForm(instance=saida),
            'pk': pk,
        }
        return render(request, template_name, context)
    
def delete_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    saida.produto.quantidade = saida.produto.quantidade - saida.quantidade
    saida.produto.save()
    saida.delete()
    
    return redirect('saida:list_saida')

estoque/saida/templates/list_saida.html
{% extends 'base.html' %}
{% block product %}
<div class="block">
    <strong>Saidas</strong>
   </div>
<a class="button is-success" href="{% url 'saida:new_saida' %}">Nova Saida</a>
<table class="table is-narrow">
    <thead> 
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for saida in saidas %}
        <tr>
            <th>{{ saida.id }}</th>
            <td>{{ saida.produto }}</td>
            <td>{{ saida.preco }}</td>
            <td>{{ saida.quantidade }}</td>
            <td><a class="button is-success" href="{% url 'saida:update_saida' saida.id%}">Editar</a></td>
            <td><a class="button is-success" href="{% url 'saida:delete_saida' saida.id%}">Deletar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

estoque/saida/templates/new_saida.html
{% extends 'base.html' %}
{% block product %}
    <p>Nova saida</p>
    <form action="{% url 'saida:new_saida' %}"method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success" type="submit">Salvar</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li style="color:red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

estoque/saida/templates/update_saida.html
{% extends 'base.html' %}
{% block product %}
    <p>Alterar saida</p>
    <form action="{% url 'saida:update_saida' pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success" type="submit">Salvar</button>
    </form>

{% endblock %}