estoque/estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index 

urlpatterns = [
    path('', index, name='index'),
    path('produto/',include('produto.urls',namespace='produto')),
    path('entrada/',include('entrada.urls',namespace='entrada')),
    path('saida/',include('saida.urls',namespace='saida')),
    path('admin/', admin.site.urls),
]

estoque/produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto


app_name ='produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto,name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto,name='delete_produto'),
]

estoque/saida/urls.py
from django.urls import path
from .views import *


app_name ='saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida,name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida,name='delete_saida'),
]

estoque/produto/models.py
from django.db import models

# Create your models here.
class Cores(models.Model):
    cor = models.CharField('Cor', max_length=200)
    def __str__(self):
        return self.cor
    

class Produtos(models.Model):
    produto = models.CharField('Produto', max_length=200,)
    cor = models.ForeignKey(Cores, on_delete=models.CASCADE,verbose_name='Cor')
    descricao = models.TextField('Descrição', blank=True)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.produto
    
    def precoQuantidade(self):
        return self.preco * self.quantidade
    
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['-produto']

estoque/produto/forms.py
from django.forms import ModelForm, TextInput, Textarea, Select
from .models import Produtos

class ProdutoForm(ModelForm):
    class Meta:
        model = Produtos
        fields = ['produto', 'cor', 'descricao']
        widgets = {
            'produto': TextInput(attrs={'class':'input'}),
            'cor': Select(attrs={'class':'select'}),
            'descricao': Textarea(attrs={'class':'textarea'}),
        }

estoque/produto/views.py
from django.shortcuts import render, redirect
from .models import Produtos
from .forms import ProdutoForm
# Create your views here.

def list_produto(request):
    produtos = Produtos.objects.all()
    template_name = 'list_produto.html'
    context = {
    'produtos': produtos,
    }
    return render(request, template_name, context)

def new_produto(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('produto:list_produto')
    else:
        template_name = 'new_produto.html'
        context = {'form': ProdutoForm()}

        return render(request, template_name, context)

def update_produto(request, pk):
    produto = Produtos.objects.get(pk=pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('produto:list_produto')
    else:
        template_name = 'update_produto.html'
        context = {
        'form': ProdutoForm(instance=produto),
        'pk': pk,
        }
        return render(request, template_name, context)
    
def delete_produto(request, pk):
    produto = Produtos.objects.get(pk=pk)
    produto.delete()
    return redirect('produto:list_produto')

estoque/produto/templates/list_produto.html
{% extends 'base.html' %}
{% block product %}
<div class="block">
   <strong>Produto</strong>
  </div>
<a class="button is-success" href="{% url 'produto:new_produto' %}">Novo</a>
<table class="table is-narrow">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for produto in produtos %}
        <tr>
            <th>{{ produto.id }}</th>
            <td>{{ produto.produto }}</td>
            <td>{{ produto.cor }}</td>
            <td>{{ produto.preco }}</td>
            <td>{{ produto.quantidade }}</td>
            <td><a class="button is-success" href="{% url 'produto:update_produto' produto.id%}">Atualizar</a></td>
            <td><a class="button is-success" href="{% url 'produto:delete_produto' produto.id%}">Deletar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

estoque/produto/templates/new_produto.html
{% extends 'base.html' %}
{% block product %}
    <form action="{% url 'produto:new_produto' %}"method="POST">
        {% csrf_token %}
        <p>Novo produto</p>
            {% for field in form %} 
            <div class="field">
                <label class="label">{{ field.label }}</label>
                    {% if  field.name  == 'cor' %}
                    <div class="select">
                        {{ field }}
                    </div>
                    {% else %}
                    <div class="control">
                        {{ field }}
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %} 
            <button class="button is-success" type="submit">Salvar</button>
    </form>
{% endblock %}

estoque/produto/templates/update_produto.html
{% extends 'base.html' %}
{% block product %}
    <p>Alterar produto</p>
    <form action="{% url 'produto:update_produto' pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success" type="submit">Salvar</button>
    </form>
{% endblock %}