estoque/entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada


app_name ='entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name='list_entrada'),
    path('new_entrada/', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada,name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada,name='delete_entrada'),
]

estoque/estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index 

urlpatterns = [
    path('', index, name='index'),
    path('produto/',include('produto.urls',namespace='produto')),
    path('entrada/',include('entrada.urls',namespace='entrada')),
    path('saida/',include('saida.urls',namespace='saida')),
    path('admin/', admin.site.urls),
]

estoque/produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto


app_name ='produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto,name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto,name='delete_produto'),
]

estoque/saida/urls.py
from django.urls import path
from .views import *


app_name ='saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida,name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida,name='delete_saida'),
]

estoque/core/models.py
from django.db import models

# Create your models here.

estoque/core/views.py
from django.shortcuts import render
# Create your views here.
def index(request):
    template_name = 'index.html'
    context = {
    'mensagem': 'Bem vindo à aplicação estoqueWeb'
    }
    return render(request, template_name, context)

estoque/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <title>Controle de Estoque</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body>
    <nav class="navbar is-light" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="{% url 'index' %}">
            <img src="{% static 'img/box.png' %}" width="60" height="56">
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{% url 'produto:list_produto' %}">
              Produtos disponíveis

              <a class="navbar-item" href="{% url 'produto:new_produto' %}">
                Cadastrar Novo Produto
              </a>
      
            <a class="navbar-item" href="{% url 'entrada:list_entrada' %}">
              Entradas
            </a>
      
            <a class="navbar-item" href="{% url 'saida:list_saida' %}">
              Saidas
            </a>
          </div>
        </div>
      </nav>
    <div class="box">
        <h1>Estoque</h1>
        <div class="container">
          <div class="notification">
            {% block product %}{% endblock %}
          </div>  
        </div>
</body>
</html>
    

estoque/core/templates/index.html
{% extends 'base.html' %}
{% block product %}
<h1>Estoque Web</h1>
<div class="column">
    <div class="box">
      <p class="title is-5">Boas Vindas.</p>
      <p class="subtitle">Bem-vindo ao controle de Estoque online!</p>
      <p>Nessa aplicação você poderá gerenciar, cadastrar e supervisionar entrada e saida de diversos produtos. </p>
        <p>Escolha uma das opções na barra de navegação no topo da tela para começar!</p>
    </div>
  </div>
</div>
{% endblock %}